sudo: required

language: go

services:
  - docker

addons:
  postgresql: "9.4"

go:
  - 1.4.2
  - 1.5.2

install:
  - make setup
  
script:
  - make build
  - make test
  - PGHOST=127.0.0.1 ./script/test_all.sh